version: '3.7'

services:
  postgres:
    build: docker/postgres
    hostname: postgres
    container_name: postgres
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=appuser
      - POSTGRES_DB=app
      - TZ=Asia/Tokyo
    ports:
      - 5010:5432

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: pgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
    driver: local
  pgadmin:
    driver: local
