/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.takabow0705

import com.github.takabow0705.plugins.*
import io.ktor.server.application.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

@kotlin.jvm.JvmOverloads
fun Application.module() {
  configureRouting()
  configureSerialization()
}
