/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlin.custom.plugin")
    id("io.ktor.plugin") version "2.3.2"
}

dependencies {
    implementation(libs.ktor.core)
    implementation(libs.ktor.netty)
    implementation(libs.ktor.content)
    implementation(libs.ktor.serialization)
    implementation(libs.logback)
    implementation(libs.bundles.exposed)
    implementation(libs.postgres.driver)
    implementation(libs.logback)
    implementation(libs.ktor.core)
    testImplementation(testLibs.kotlin.test.junit)
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.Takabow0705.ApiServerKt")
}
