/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlin.custom.plugin")
    id("io.ktor.plugin") version "2.3.2"
    kotlin("kapt")
}

dependencies {
    implementation(libs.ktor.core)
    implementation(libs.ktor.netty)
    implementation(libs.ktor.content)
    implementation(libs.ktor.serialization)
    implementation(libs.logback)
    implementation(libs.bundles.exposed)
    implementation(libs.postgres.driver)
    implementation(libs.logback)
    implementation(libs.ktor.core)
    implementation(libs.dagger2)
    //annotationProcessor(libs.dagger2.compiler)
    testImplementation(testLibs.kotlin.test.junit)

    kapt(libs.dagger2.compiler)
    //kapt("org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.6.2")
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.takabow0705.ApiServerKt")
}
